### PR TITLE
Wip cdc variant url

### LINKED ISSUE #13: [REQUEST] Update Aggregate Lineages to use CDC grouping URL
### Feature Request
Currently we are having to manually update the cdc_lineage_groups.json file each week which is an input in the lineage_calling_and_results.wdl. Sam has written code for the cloud-run-aggregate-lineages repo that downloads the cdc aggregrate lineage groupings json directly from the [CDC Covid variant dashboard website](https://covid.cdc.gov/covid-data-tracker/#variant-proportions). We want to move away from manually updating the cdc_lineage_groups.json and incorporate Sam's automated code into the lineage_calling_and_results.wdl.  

### Solution
Pull the code from the [cloud-run-aggregate-lineages repo](https://github.com/CDPHE-bioinformatics/cloud-run-aggregate-lineages/blob/main/src/main.py) that automates pulling the json from CDC's dashboard. Incorporate the code into the concat_seq_metrics_and_lineage_results.py script for the results_table task in the lineage_calling_and_results.wdl. Update the task and wdl inputs as needed. 

### Downstream effects
Code duplicates - We also aggregate lineages based on CDC grouping in the wastewater heatmap co-lab notebook.

### PR DESCRIPTION
**Pull request by molly-hetheringtonrauth**
This PR closes #13 

##  Aim, context, and functionality 🎯
We wanted to move away from using the cdc_lineages.json input that had to be manually updated weekly or whenever CDC added a new aggregate lineage. To do this we used [code](https://github.com/CDPHE-bioinformatics/cloud-run-aggregate-lineages/blob/main/src/main.py) that Sam developed for reaggregating lineages and that pulls the cdc aggregated lineages directly from the [CDC variant dashboard] () URL. These changes required refactoring to the concat_seq_metrics_and_lineage_results.py script and to the lineage_calling_and_results.wdl workflow.

Additionally while re-factorig the concat_seq_metrics_and_lineage_results.py script, we added function descriptions for all functions. 

I added all files required to test the concat_seq_metrics_and_lineage_results.py script locally from the command line. This greatly speeds up testing instead of having to run all tests on terra. -- As a team we discussed excluding these test files from the repo so they were removed and the commit history removed.

#### Upstream effects 
(e.g. preprocessing of data)
None

#### Input changes 
(e.g. file changes, names of data fields, etc.)

From the lineage_calling_and_results.wdl workflow: 
  - cdc_lineage_groups_json input has been removed. It is no longer need in the workspace data. 

#### Output changes 
(e.g. file changes, names of data fields, etc.)
None

#### Downstream effects 
(e.g. BigQuery organization, file structure organization, file content organization)
None

##  Testing 🛠️
**Test dataset(s):**
- cov_2136_grid (for terra testing; pulled data directly from the bucket. 

**Test(s) performed:**
- Tested the concat_seq_metrics_and_lineage_calling.py script locally on the CLI using the test data
- Tested the entire lineage_calling_and_results.wdl workflow on terra to ensure all changes made were compatible with the wdl. Then performed TheiaValidate on the sequencing results csv files comparing percent coverage, nextclade, pangolin lineage, expanded lineage, aggregated lineage, nextclade version and pangolin lineage.  

**Results (including if the results matched the expected results):**
- CLI tested resulted in a sequencing results csv file with expected results. 
- Terra testing - One sample differed in pangolin lineage and aggregated lineage but, it seems the sample did not pass assembly during the original analysis and so there was no pangolin lineage and aggregated lineage to compare. 
- Results of TheiaValidate can be found in the seq_projects validation directory. 

## Developer Checklist 👷‍♀️ 
- [x] Prior to development, issues were discussed with the bioinformatics team members and approved
- [x] Code has been refactored to sufficiently address the issues this pull request closes
- [x] Testing was performed and the results from testing match the expected results
- [x] All code changes match our style guide
- [x] README has been updated to reflect changes - no changes were necessary
- [x] Workflow diagrams in READMEs have been updated to reflect changes - no changes were necessary

## Reviewer Checklist 🔍
- [x] Met with developer to review all changes and testing performed
- [x] Code refactoring sufficiently address the issue(s) that this pull request closes
- [x] All code meets style guide criteria
- [x] Confirm testing was sufficient (e.g. correct dataset was used for testing, results match the expected results). If not, the developer will perform additional testing which should be documented in the testing section above.
- [ ] New version release number has been decided upon (if applicable)

### CODE REVIEW

**Comment by molly-hetheringtonrauth** [comment]
@sam-baird I've removed the test files and clean the commit history. Ready for your review!

**Comment by sam-baird** [comment]
It looks like the reason the one sample failed on TheiaValidate was a likely transient Docker pull error in the assembly workflow, so it probably just needed to be reran. I also uploaded the exact_differences TSV, inputs.json, and output set Terra data table to the GCP folder as a more complete and reproducible record of the validation

**Comment by sam-baird** [comment]
I think this should be released as v2.3.0

**Comment by molly-hetheringtonrauth** [comment]
@sam-baird - updated the workflow version to 2-3-0 in the workflow version task.

**Pull request merged**
